#+TITLE: Now
#+NAV: 2
#+CONTENT-TYPE: page
#+I18N-KEY: nav/now
** Freelancing
I started my first freelancing project. It's outside of my comfort zone because my main task is to automate a cloud deployment. While it's a bit scary to work outside of the comfort zone, it's also the best way to learn new things quickly. My AWS skills and knowledge about various tools for deployment automation such as CDK and Terraform grew a lot in the past couple of weeks.
** thomas-sojka.tech
As you have noticed, things on the website are changing. I am doing a redesign of my website and want to focus on improved visuals and put some more thought into SEO. Doing something design-heavy on the side next to my freelance project is great to have some balance.
** Books
I finished reading 'Modern Software Engineering' and 'Terraform Up & Running' and I am working to extract some notes from them.

I am still reading quite a lot in parallel, probably too much, but I am not sure yet where to focus. Currently, I am reading 'SICP', 'Storytelling with Data' & 'R for Data Science'.


updated on <2024-03-24 Sun>
