#+TITLE: Now
#+NAV: 2
#+CONTENT-TYPE: page
#+I18N-KEY: nav/now
** Freelancing
My first freelance project is progressing and my AWS skills have grown significantly in recent weeks. But looking back, I definitely enjoy working on the frontend more. Fast feedback cycles are the most important thing I enjoy about my work. Feedback is much faster in frontend compared to the infrastructure work.
** Remarkable template
I've been using the Remarkable tablet for a long time, but never really tried to make the most of it. Recently I discovered that there is a very active scene that provides planning templates for Remarkable. I really like the combination of handwriting and digital organisation, so I'm currently creating my own template.
** Books
After a break, I'm finally reading 'SICP' regularly again. I've also decided that I want to learn a bit more about marketing and business. I read 'The Millionaire Fastlane' and despite the deceptive title, I learnt a lot from it. Now I'm reading the 1-page marketing plan to dive deeper into this topic.


updated on <2024-04-24 Wed>
