#+TITLE: Now
#+NAV: 2
#+CONTENT-TYPE: page
** The Journey
My wife and I are going on a 6-month journey to explore North and South America. I quit my job, and it's the first time in my life that I am taking a break from "normal" life after going straight to university, then starting to work as a Software Engineer. I haven't fully processed what I am doing here, but I am already very excited about it.

** The Sync
As part of my preparation for our journey, I built myself a little system to quickly set up a new computer with all the applications, configurations, and data that are important to me. The process of defining what is important to me when it comes to my data and the applications I use was a great experience on its own. I plan to write more about that soon.

** Reading
We haven't started our journey yet, so there are a lot of farewells right now, and I am thinking about how I want to spend my time. There's the obvious exploration part, but I also want to spend much more time reading and plan to build up a reading list for my journey. I plan to share that soon.
