#+TITLE: Now
#+NAV: 2
#+CONTENT-TYPE: page
#+I18N-KEY: nav/now
** Freelancing
Mein erstes freiberufliches Projekt schreitet voran, und meine AWS-Kenntnisse haben sich in den letzten Wochen deutlich verbessert. Aber wenn ich zurückblicke, macht mir die Arbeit am Frontend definitiv mehr Spaß. Schnelle Feedback-Zyklen sind dass, was ich an meiner Arbeit schätze. Das Feedback ist im Frontend deutlich schneller als bei der Infrastruktur.
** Remarkable template
Ich benutze das Remarkable-Tablet schon seit langem, habe aber nie wirklich versucht, das Beste daraus zu machen. Vor kurzem habe ich entdeckt, dass es eine sehr aktive Community gibt, die Planungstemplates für Remarkable bereitstellt. Ich mag die Kombination aus Handschrift und digitaler Organisation sehr, also erstelle ich gerade mein eigenes Template.
** Bücher
Nach einer Pause lese ich nun endlich wieder regelmäßig 'SICP'. Ich habe auch beschlossen, dass ich etwas mehr über Marketing und Business lernen möchte. Ich habe 'The Millionaire Fastlane' gelesen und trotz des seltsamen Titels konnte ich viel daraus lernen. Jetzt lese ich den 1-Page-Marketing Plan, um tiefer in dieses Thema einzutauchen.

aktualisiert am <2024-04-24 Wed>
