#+TITLE: Now
#+NAV: 2
#+CONTENT-TYPE: page
#+I18N-KEY: nav/now
** Neuer Job
Letzte Woche habe ich meinen neuen Job bei Griffin, einer Bank in London, begonnen. Neue Anfänge sind immer aufregend, und ich habe eine lange Liste an Dingen zu lernen, um mehr über Banking und die Technologien, mit denen ich jetzt arbeite, zu verstehen. Es ist auch eine Rückkehr zu der Progammiersprach, die ich am meisten genieße, und ich bin wirklich glücklich, wieder Vollzeit mit Clojure zu arbeiten.
** Balance finden
Nach einem Monat Reisen durch Spanien und dem Besuch meines ersten Musikfestivals arbeite ich daran, wieder zu meinen Lern- und Sport-Routinen zurückzukehren.
** Bücher
Ich habe „The 1-Page Marketing Plan“ fertig gelesen und habe jetzt ein besseres Verständnis davon, was Marketing auf einer hohen Ebene tatsächlich bedeutet. Das nächste Buch, das ich auch schon fast fertig habe, ist „Million Dollar Weekend“, das erklärt, wie man ein neues Geschäft startet. Ich lese weiterhin „SICP“.

aktualisiert am <2024-07-04 Thu>
