#+TITLE: Now
#+NAV: 2
#+CONTENT-TYPE: page
#+I18N-KEY: nav/now
** Freelancing
Ich habe mein erstes freiberufliches Projekt gestartet. Es liegt außerhalb meiner Komfortzone, da meine Hauptaufgabe darin besteht, eine Cloud-Bereitstellung zu automatisieren. Obwohl es ein wenig beängstigend ist, außerhalb der Komfortzone zu arbeiten, ist es auch der beste Weg, schnell neue Dinge zu lernen. Meine AWS-Fähigkeiten und mein Wissen über verschiedene Tools für die Bereitstellungsautomatisierung wie CDK und Terraform haben sich in den letzten Wochen stark weiterentwickelt.
** thomas-sojka.tech
Wie ihr vielleicht bemerkt haben, ändert sich vieles auf der Website. Ich überarbeite meine Website und möchte mich auf verbessertes Design fokusieren und mehr über SEO nachdenken. Etwas Design-intensives neben meinem freiberuflichen Projekt zu tun, ist großartig, um etwas Ausgleich zu haben.
** Bücher
Ich habe das Buch "Modern Software Engineering" und "Terraform Up & Running" fertig gelesen und arbeite daran, einige Notizen daraus zu extrahieren.

Ich lese immer noch ziemlich viel parallel, wahrscheinlich zu viel, bin mir aber noch nicht sicher, wo ich mich am besten fokussieren sollte. Aktuell lese ich "SICP", "Storytelling with Data" und "R for Data Science".

aktualisiert am <2024-03-24 Sun>
