name: Branch Build

on: push

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      vercel-args: ''
    secrets:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      vercel-org-id: ${{ secrets.ORG_ID}}
      vercel-project-id: ${{ secrets.PROJECT_ID}}
