name: CI

on:
  workflow_call:
    inputs:
      vercel-args:
        type: string
    secrets:
      vercel-token:
        required: true
      vercel-org-id:
        required: true
      vercel-project-id:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@4.0
      with:
        cli: 1.10.1.693
    - uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2022.01.15'
    - name: Run clj-kondo
      run: clj-kondo --lint src
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build
    - name: Tests
      run: clojure -Mtest-runner-cognitect
      shell: bash
    - name: Build Pages
      run: clojure -Xbuild
      shell: bash
    - name: Build JS
      run: npx shadow-cljs compile app
    - uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.vercel-token }}
        vercel-org-id: ${{ secrets.vercel-org-id}}
        vercel-project-id: ${{ secrets.vercel-project-id}}
        working-directory: .
        vercel-args: ${{ inputs.vercel-args }}
